services:
  scms:
    build: .
    ports:
      - "8080:80"
    environment:
      - AdminEmail=${AdminEmail}
      - AdminPassword=${AdminPassword}
      - EnableAdminSeeding=${EnableAdminSeeding}
    volumes:
      - ./SiteDate/Database:/database
      - ./SiteDate/wwwroot/images:/wwwroot/images